# Generated by Django 5.2 on 2025-04-04 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elecciones', '0001_initial'),
        ('partidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escanos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escanos', models.IntegerField()),
                ('eleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.elecciones')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partidos.partidos')),
            ],
        ),
    ]
